name: Build and test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        build_type: [Release]
        os: [windows-latest, ubuntu-latest]
        include:
          - os: windows-latest
            cpp_compiler: cl
            c_compiler: cl
          - os: ubuntu-latest
            cpp_compiler: g++
            c_compiler: gcc

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Configure CMake
        run: >
          cmake
          -S ${{ github.workspace }}
          -B ${{ github.workspace }}/build
          -DCMAKE_CXX_COMPILER=${{ matrix.cpp_compiler }}
          -DCMAKE_C_COMPILER=${{ matrix.c_compiler }}
          -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}
      - name: Build
        run: >
          cmake
          --build ${{ github.workspace }}/build
          --config ${{ matrix.build_type }}
          --parallel
      - name: Test
        working-directory: ${{ github.workspace }}/build
        run: ctest --build-config ${{ matrix.build_type }}

      - name: Install
        run: cmake --install build --config ${{ matrix.build_type }}
      - name: Upload binaries
        uses: actions/upload-artifact@v4
        with:
          name: binaries-${{ runner.os }}-${{ matrix.build_type }}
          path: ${{ github.workspace }}/projects/bin/*
